### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by dvalter** [rapIsKal/bitchfuck#3]
According to the spirit of the Free Software and (probably) Github rules, this project needs an Open Source License.
I think the best possible one is [WTFPLv2](http://www.wtfpl.net/about/).
But in case you found it lacking **NO LIABILITY* statement, you may use something like the [one](https://github.com/dvalter/QVPaint/blob/master/LICENSE.WTFPLv2-EXCEPT) I've made for my useless project.

**Comment by rapIsKal** [comment]
done in last commit
